# kubectl apply -f kubeserve-deployment.yaml --record=true
# kubectl rollout history deployment.apps/kubeserve
# kubectl rollout status -w deployment.apps/kubeserve
# kubectl describe deployment.apps/kubeserve
# kubectl expose deployment.apps/kubeserve --port 80 --target-port 80 --type NodePort
# kubectl get pods -o wide
# kubectl scale deployment.apps/kubeserve --replicas=5
# while true; do curl http://<ip-address-of-the-service>; done
# kubectl set image deployments/kubeserve app=linuxacademycontent/kubeserve:v2 --v 6
# kubectl get replicasets
# kubectl get pods
# kubectl rollout history deployment.apps/kubeserve
# kubectl rollout undo deployment.apps/kubeserve
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      name: kubeserve
      labels:
        app: kubeserve
    spec:
      containers:
      - image: linuxacademycontent/kubeserve:v1
        name: app