# kubectl create deployment nginx --image=nginx:1.23.2-alpine --dry-run=client --output=yaml

# kubectl apply -f nginx-deployment.yaml
# kubectl get pods --all-namespaces
# kubectl logs <pod_name> -n <namespace_name>
# kubectl logs <pod_name> -n <namespace_name> > broken-pod.log
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.232-alpine # image tag don't exist
        name: nginx
        resources: {}
status: {}