# kubectl apply -f busybox.yaml
# kubectl get po
# kubectl exec -it busybox -- /bin/sh
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox:1.28.4
    command:
      - sleep
      - "3600"
    name: busybox
  restartPolicy: Always