# kubectl get pv
# kubectl create clusterrole pv-reader --verb=get,list --resource=persistentvolumes
# kubectl create clusterrolebinding pv-test --clusterrole=pv-reader --serviceaccount=web:default
# kubectl create namespace web
# kubectl apply -f curlpod.yaml
# kubectl exec -it curlpod -n web -- sh
## curl localhost:8001/api/v1/persistentvolumes
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: Pod
metadata:
  name: curlpod
  namespace: web
spec:
  containers:
  - image: curlimages/curl
    command: ["sleep", "9999999"]
    name: main
  - image: linuxacademycontent/kubectl-proxy
    name: proxy
  restartPolicy: Always
