apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-www-pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/mnt/data"
    #path: /data/pv0001/